# Generated by Django 5.0.2 on 2026-05-08 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlog',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='adminlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='users.adminuser'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='details',
            field=models.TextField(blank=True, help_text='JSON data', null=True),
        ),
    ]
