# Generated by Django 5.0.2 on 2026-05-09 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_alter_resident_created_by_alter_resident_email_and_more'),
        ('users', '0002_remove_adminlog_admin_id_adminlog_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.CharField(max_length=500)),
                ('photo_type', models.CharField(default='profile', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='residents.resident')),
            ],
            options={
                'db_table': 'user_photos',
            },
        ),
    ]
