# Generated by Django 5.0.2 on 2026-05-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('civil_status', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'family_members',
            },
        ),
        migrations.CreateModel(
            name='ResidentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pangkabuhayan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('land_ownership', models.CharField(blank=True, max_length=100, null=True)),
                ('land_ownership_other', models.CharField(blank=True, max_length=255, null=True)),
                ('house_ownership', models.CharField(blank=True, max_length=100, null=True)),
                ('house_ownership_other', models.CharField(blank=True, max_length=255, null=True)),
                ('farmland', models.CharField(blank=True, max_length=100, null=True)),
                ('cooking_energy', models.CharField(blank=True, max_length=100, null=True)),
                ('cooking_energy_other', models.CharField(blank=True, max_length=255, null=True)),
                ('toilet_type', models.CharField(blank=True, max_length=100, null=True)),
                ('toilet_type_other', models.CharField(blank=True, max_length=255, null=True)),
                ('electricity_source', models.CharField(blank=True, max_length=100, null=True)),
                ('electricity_source_other', models.CharField(blank=True, max_length=255, null=True)),
                ('water_source', models.CharField(blank=True, max_length=100, null=True)),
                ('water_source_other', models.CharField(blank=True, max_length=255, null=True)),
                ('waste_disposal', models.CharField(blank=True, max_length=100, null=True)),
                ('waste_disposal_other', models.CharField(blank=True, max_length=255, null=True)),
                ('appliances', models.TextField(blank=True, null=True)),
                ('transportation', models.TextField(blank=True, null=True)),
                ('transportation_other', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.TextField(blank=True, null=True)),
                ('business_other', models.CharField(blank=True, max_length=255, null=True)),
                ('contraceptive', models.TextField(blank=True, null=True)),
                ('interviewer', models.CharField(blank=True, max_length=255, null=True)),
                ('interviewer_title', models.CharField(blank=True, max_length=255, null=True)),
                ('resident_disability', models.CharField(blank=True, max_length=255, null=True)),
                ('resident_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resident_registrations',
            },
        ),
        migrations.CreateModel(
            name='FamilyDisability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabilities', to='residents.familymember')),
            ],
            options={
                'db_table': 'family_disabilities',
            },
        ),
        migrations.CreateModel(
            name='FamilyOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='residents.familymember')),
            ],
            options={
                'db_table': 'family_organizations',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('barangay', models.CharField(default='Gumaoc East', max_length=100)),
                ('sitio', models.CharField(default='BLOCK', max_length=100)),
                ('interviewer', models.CharField(blank=True, max_length=255, null=True)),
                ('interviewer_title', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField()),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], max_length=20)),
                ('rfid_code', models.CharField(blank=True, max_length=50, null=True)),
                ('rfid', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('reset_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('profile_complete', models.BooleanField(default=True)),
                ('relationship_to_head', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.resident')),
            ],
            options={
                'db_table': 'residents',
            },
        ),
        migrations.AddField(
            model_name='familymember',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='residents.resident'),
        ),
        migrations.CreateModel(
            name='ResidentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(max_length=255)),
                ('record_status', models.CharField(choices=[('good', 'Good'), ('minor_issues', 'Minor Issues'), ('major_issues', 'Major Issues'), ('critical', 'Critical')], default='good', max_length=20)),
                ('total_complaints', models.IntegerField(default=0)),
                ('total_incidents', models.IntegerField(default=0)),
                ('pending_cases', models.IntegerField(default=0)),
                ('resolved_cases', models.IntegerField(default=0)),
                ('requires_captain_clearance', models.BooleanField(default=False)),
                ('captain_clearance_granted', models.BooleanField(default=False)),
                ('captain_clearance_date', models.DateTimeField(blank=True, null=True)),
                ('captain_clearance_reason', models.TextField(blank=True, null=True)),
                ('captain_clearance_expires', models.DateTimeField(blank=True, null=True)),
                ('last_incident_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_records', to='residents.resident')),
            ],
            options={
                'db_table': 'resident_status',
            },
        ),
    ]
